export const CENTRE_DATA = [
  {
    id: 1,
    img: require('../../assets/images/centres/Brisbane-Adelaide-Street-opens.jpg'),
    number: 9.8,
    logo: require('../../assets/logo/logo_centre.png'),
    title: 'Castle Hill Montessori Academy',
    mapText: '1 Kerrs Road, Castle Hill, NSW 2154',
    babyText: '90 childrens',
    kindiBtnColor: '#E9F4FF',
    kindiColor: '#32A4FC',
    kindiText: 'KindiCare Basic',
    waitlistText: '48 waitlisted',
    serviceText: '4 services',
  },
  {
    id: 2,
    img: require('../../assets/images/centres/Brisbane-Adelaide-Street-opens.jpg'),
    number: 9.8,
    logo: require('../../assets/logo/logo_centre.png'),
    title: 'Castle Hill Montessori Academy',
    mapText: '1 Kerrs Road, Castle Hill, NSW 2154',
    babyText: '90 childrens',
    kindiBtnColor: '#EDF9F0',
    kindiColor: '#36BF57',
    kindiText: 'KindiCare Basic',
    waitlistText: '48 waitlisted',
    serviceText: '4 services',
  },
];
